# Generated by Django 5.2 on 2025-04-29 00:04

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('address', models.CharField(max_length=255, verbose_name='Endereço')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=255, verbose_name='Email')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('num_employees', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de Funcionários')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mecmind_app.company')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_name', models.CharField(choices=[('chapa', 'Chapa'), ('eixo', 'Eixo'), ('tubo', 'Tubo'), ('solda', 'Solda'), ('montagem', 'Montagem'), ('geral', 'Geral')], max_length=20)),
                ('drawing', models.ImageField(blank=True, upload_to='projects/%Y/%m/')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('raw_material', models.TextField(blank=True, verbose_name='Matéria Prima')),
                ('processes', models.TextField(blank=True, verbose_name='Processos')),
                ('user_observation', models.TextField(blank=True, verbose_name='Observações do Usuário')),
                ('ia_observation', models.TextField(blank=True, verbose_name='Observações da IA')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mecmind_app.company')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='mecmind_app.user')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['-created_date'],
            },
        ),
    ]
