# Generated by Django 5.2 on 2025-05-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecmind_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='machines',
            field=models.TextField(blank=True, verbose_name='Máquinas'),
        ),
    ]
