# Generated by Django 5.2 on 2025-06-25 22:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecmind_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drawing', models.ImageField(blank=True, upload_to='technical_analysis/%Y/%m/%d')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('analysis_name', models.CharField(blank=True, max_length=100, verbose_name='Tipo de Análise')),
                ('subparts', models.JSONField(blank=True, default=list, verbose_name='Sub-partes')),
                ('manufacturing_strategy', models.JSONField(blank=True, default=list, verbose_name='Estratégia de Fabricação')),
                ('manufacturing_sequence', models.JSONField(blank=True, default=list, verbose_name='Sequência de Fabricação')),
                ('critical_points', models.JSONField(blank=True, default=list, verbose_name='Pontos Críticos')),
                ('summary', models.TextField(blank=True, verbose_name='Resumo')),
                ('user_observation', models.TextField(blank=True, verbose_name='Observações do Usuário')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mecmind_app.company')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Análise Técnica',
                'verbose_name_plural': 'Análises Técnicas',
                'ordering': ['-created_date'],
            },
        ),
    ]
