# Generated by Django 5.2 on 2025-06-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecmind_app', '0002_project_machines'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='external_processes',
            field=models.TextField(blank=True, verbose_name='Processos Externos'),
        ),
        migrations.AddField(
            model_name='company',
            name='internal_processes',
            field=models.TextField(blank=True, verbose_name='Processos Internos'),
        ),
        migrations.AddField(
            model_name='company',
            name='machines_milling',
            field=models.TextField(blank=True, verbose_name='Máquinas de Fresamento'),
        ),
        migrations.AddField(
            model_name='company',
            name='machines_other',
            field=models.TextField(blank=True, verbose_name='Outras Máquinas'),
        ),
        migrations.AddField(
            model_name='company',
            name='machines_turning',
            field=models.TextField(blank=True, verbose_name='Máquinas de Torneamento'),
        ),
        migrations.AddField(
            model_name='company',
            name='max_dimensions',
            field=models.CharField(blank=True, max_length=50, verbose_name='Dimensões Máximas'),
        ),
        migrations.AddField(
            model_name='company',
            name='work_shifts',
            field=models.TextField(blank=True, verbose_name='Turnos de Trabalho'),
        ),
    ]
