# Generated by Django 5.2 on 2025-07-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecmind_app', '0002_technicalanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='api_key',
            field=models.TextField(blank=True, verbose_name='Chave de API'),
        ),
    ]
