# Generated by Django 5.2 on 2025-08-04 21:43

import mecmind_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecmind_app', '0003_company_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='diameter',
            field=models.CharField(blank=True, help_text='Ex: "1/4", "1 1/4", ou "2"', max_length=10, null=True, validators=[mecmind_app.validators.validate_inches], verbose_name='Diâmetro'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='thickness',
            field=models.CharField(blank=True, help_text='Ex: "1/4", "1 1/4", ou "2"', max_length=10, null=True, validators=[mecmind_app.validators.validate_inches], verbose_name='Espessura'),
        ),
    ]
