# Generated by Django 5.2 on 2025-06-08 21:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecmind_app', '0003_company_external_processes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('category', models.CharField(choices=[('eixo', 'Eixo'), ('chapa', 'Chapa'), ('tubo', 'Tubo')], max_length=20, verbose_name='Categoria')),
                ('material', models.CharField(blank=True, max_length=50, verbose_name='Material')),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Comprimento')),
                ('diameter', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Diâmetro')),
                ('thickness', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Espessura')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Largura')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Altura')),
                ('unit', models.CharField(choices=[('un', 'Unidade'), ('kg', 'Kilograma'), ('m', 'Metro'), ('m2', 'Metro Quadrado'), ('pç', 'Peça')], max_length=10, verbose_name='Unidade')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('reservado', 'Reservado'), ('inativo', 'Inativo')], default='disponivel', max_length=20, verbose_name='Status')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='mecmind_app.company')),
            ],
            options={
                'verbose_name': 'Estoque',
                'verbose_name_plural': 'Estoques',
                'ordering': ['-created_date'],
            },
        ),
    ]
