# Generated by Django 5.2 on 2025-06-08 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mecmind_app', '0004_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='height',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='unit',
        ),
    ]
