# Generated by Django 5.2 on 2025-06-13 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecmind_app', '0005_remove_stock_height_remove_stock_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='max_dimensions',
        ),
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.CharField(choices=[('barra_redonda', 'Barra Redonda'), ('chapa', 'Chapa'), ('tubo', 'Tubo')], max_length=20, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantidade'),
        ),
    ]
