# Generated by Django 5.2 on 2025-08-25 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecmind_app', '0005_prompt_systemmessages'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Ano')),
                ('month', models.IntegerField(verbose_name='Mês')),
                ('analyses_used', models.PositiveIntegerField(default=0, verbose_name='Análises Utilizadas')),
                ('analyses_limit', models.PositiveIntegerField(verbose_name='Limite de Análises')),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='mecmind_app.company')),
            ],
            options={
                'verbose_name': 'Uso Mensal da Empresa',
                'verbose_name_plural': 'Uso Mensal das Empresas',
                'ordering': ['-year', '-month', 'company__name'],
                'unique_together': {('company', 'year', 'month')},
            },
        ),
    ]
