# Generated by Django 5.2 on 2025-06-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecmind_app', '0006_remove_company_max_dimensions_alter_stock_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='in_stock',
            field=models.BooleanField(default=False, verbose_name='Em Estoque'),
        ),
        migrations.AddField(
            model_name='project',
            name='recommended_stock_item',
            field=models.TextField(blank=True, verbose_name='Máquinas'),
        ),
    ]
