# Generated by Django 5.2 on 2025-08-25 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecmind_app', '0006_companyusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='monthly_analysis_limit',
            field=models.PositiveIntegerField(default=50, help_text='Número máximo de análises por mês', verbose_name='Limite Mensal de Análises'),
        ),
    ]
