# Generated by Django 5.2 on 2025-08-26 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mecmind_app', '0007_company_monthly_analysis_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyusage',
            name='analyses_limit',
        ),
    ]
