# Generated by Django 5.2 on 2025-09-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecmind_app', '0008_remove_companyusage_analyses_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalanalysis',
            name='drawing_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='technical_analysis/thumbnails/%Y/%m/%d'),
        ),
    ]
