# Generated by Django 5.2 on 2025-09-05 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecmind_app', '0009_technicalanalysis_drawing_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='drawing_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='projects/thumbnails/%Y/%m/%d'),
        ),
    ]
